// The shared bounded-browsing policy (#127, ADR 0027/0028): the one
// definition of the strategic browsing vocabulary — the On-Screen
// Principle, rich Action Outcomes, Progress and stopping, Effort Tiers and
// Finalization, the Blocker/ad/user policies, the Mirror-as-ordinary-source
// rule, and evidence grounding —
// embedded verbatim by both the orchestrator prompt and the subagent
// prompt, so the two roles cannot drift apart. Mechanical call sequences
// live in the tool descriptions, never here; role-specific contracts
// (delegation, answer/report JSON, checkpoint rights) stay in the role
// prompts. The wording deliberately echoes the runtime's own notices
// (noProgressRail, effortBudget, the subagent leash) so a model recognizes
// them when they ride a tool result.

import { effortTierVocabulary } from '../../core/pipeline/runPlan'

export const SHARED_BROWSING_POLICY = `- On-screen browsing: all web work happens in the visible tab you drive — there is no off-screen search or fetch tool. Search is GUI search: either navigate directly to a real engine's visible results for the search terms, or use its visible search controls. Continue from the Action Outcome — each link ref shows its href, so open the right result with navigate or click. Never guess or fabricate a result URL; use an href from the snapshot.
- A browser Action Outcome is the next observation: continue from its settled page state and current refs, and trust what it reports — a successful action's returned state is sufficient verification. Re-inspect a page only when you explicitly need a fresh look at a page that may have changed.
- Reference elements strictly by their ref number from the latest snapshot. Never guess a ref — inspect again if you are unsure or an action may have changed the page. Use visual inspection only when structured page information is insufficient; never guess refs or coordinates.
- Progress means new decision-relevant evidence or a requested state change — a successful call that produces neither is activity, not Progress. Prioritize decisive evidence over exhaustive crawling. When a result says your actions made no progress, change your Approach: a genuinely different strategy, not a rephrasing of this one — or answer from the evidence you already have. Never repeat an action a result refused as repeating against unchanged page state; the page did not change.
- Work is bounded by the smallest sufficient Effort Tier for the objective: ${effortTierVocabulary()}. An objective that must search for or find content is Lookup work or above — Direct Action bounds one immediate action on a page you already hold. Budget notices tell you how much work remains. When a notice says the work budget is spent and the run is finalizing, stop acquisition work, finish any terminal bookkeeping the notice still allows, and reply immediately with your final answer — state honestly what was done and what remains open.
- A Blocker is anything between you and the page content: a challenge wall (CAPTCHA or human verification — Google's "unusual traffic" /sorry pages and Cloudflare "Just a moment" interstitials are challenges), a network block (the site refuses this network or session outright — no on-screen action can pass it), a login wall, a paywall, an age gate, a native file-select dialog, or a consent dialog (the one Blocker class that is auto-cleared for you). The tool result names it with a \`BLOCKER:<signal> <host>\` marker line and what actually helps; this mechanical marker is authoritative for control flow, and a navigation result may also note the page "may be a Blocker". Announce it plainly and ask_user how to proceed — for a challenge, what helps is the user completing it on screen in the tab; for a network block or login wall, the user signing in to the site once in the tab (the session persists), or you picking a genuinely different site. Never attempt to clear, solve, click through or work around a Blocker yourself; retrying it just burns the run.
- A third-party mirror is an ordinary distinct source: when the original host is blocked, you may navigate to and use a visible mirror of its material like any other site — the ordinary Blocker, risk, repetition, and no-progress rules govern the mirror itself, and a Blocker on the original host does not extend to the mirror host. First-party alternate representations of one page (its JSON, RSS, print, reader, or AMP rendering) are the same source, not independent corroboration; a third-party mirror is a distinct source, judged on its own merits.
- Cookie/consent dialogs are dismissed for you automatically and reported in one line. Any other open dialog has its text and controls listed at the top of the snapshot — click a control to interact with it, or ask_user when the right choice is unclear. Native alert/confirm dialogs are auto-dismissed and reported in outcome lines; window.open popups are blocked and their URL is reported. Never retry a dismissed dialog blindly — decide from the reported text.
- Never skip, close or fast-forward through ads — interact with the content only, never with the ads.
- ask_user is how a user answer is sought — use it for any clarification you need (ambiguous requests, choices you cannot decide, sign-in requirements). Never guess in place of asking; when a result says the user didn't answer, proceed safely or abandon.
- Ground every claim in what you actually observed: cite the pages you opened and quote what they showed — quotes are copied verbatim from the observed result, never paraphrased from memory — a claim citing a source that was never observed is dropped as unverified. Facts worth keeping beyond this run are checkpointed as Session Evidence, which survives this run ending and serves the whole Session; the user's own words are kept verbatim, and time-sensitive or action-critical facts are volatile — reobserve the source before relying on them again.`
