// GENERATED by `pnpm live:answer-namings` (#323) from the Run Traces of the
// captures on disk. Do not edit by hand: run the sweep where the captures are.
//
// 71 capture sets read, 426 attempts, 20 of them with no model-written Answer:
// 22 of 406 Answer(s) name the stop (22 of 152 on a Run that did not end objective_met), 46 carry internal names (31 on such a Run).
//
// By capture set family:
//   baseline: 3 of 18 Answer(s) name the stop (3 of 14 on a Run that did not end objective_met), 6 carry internal names (4 on such a Run)
//   baseline2: 1 of 18 Answer(s) name the stop (1 of 6 on a Run that did not end objective_met), 4 carry internal names (2 on such a Run)
//   baseline3: 1 of 16 Answer(s) name the stop (1 of 8 on a Run that did not end objective_met), 1 carry internal names (1 on such a Run)
//   fix-250: 1 of 17 Answer(s) name the stop (1 of 9 on a Run that did not end objective_met), 2 carry internal names (2 on such a Run)
//   fix-252: 4 of 17 Answer(s) name the stop (4 of 9 on a Run that did not end objective_met), 2 carry internal names (2 on such a Run)
//   fix-253-256: 2 of 18 Answer(s) name the stop (2 of 11 on a Run that did not end objective_met), 4 carry internal names (3 on such a Run)
//   fix-256r: 2 of 17 Answer(s) name the stop (2 of 9 on a Run that did not end objective_met), 2 carry internal names (2 on such a Run)
//   fix-257: 2 of 18 Answer(s) name the stop (2 of 11 on a Run that did not end objective_met), 1 carry internal names (0 on such a Run)
//   fix-258-259: 1 of 16 Answer(s) name the stop (1 of 6 on a Run that did not end objective_met), 2 carry internal names (2 on such a Run)
//   fix-260-262: 0 of 17 Answer(s) name the stop (0 of 9 on a Run that did not end objective_met), 5 carry internal names (5 on such a Run)
//   fix-263-264: 1 of 17 Answer(s) name the stop (1 of 9 on a Run that did not end objective_met), 4 carry internal names (3 on such a Run)
//   fix-265-267: 0 of 28 Answer(s) name the stop (0 of 6 on a Run that did not end objective_met), 3 carry internal names (1 on such a Run)
//   fix-270: 0 of 18 Answer(s) name the stop (0 of 3 on a Run that did not end objective_met), 1 carry internal names (0 on such a Run)
//   fix-281: 0 of 16 Answer(s) name the stop (0 of 4 on a Run that did not end objective_met), 1 carry internal names (1 on such a Run)
//   fix-283: 0 of 18 Answer(s) name the stop (0 of 4 on a Run that did not end objective_met), 2 carry internal names (0 on such a Run)
//   fix-284: 0 of 18 Answer(s) name the stop (0 of 4 on a Run that did not end objective_met), 0 carry internal names (0 on such a Run)
//   fix-288-290: 1 of 17 Answer(s) name the stop (1 of 3 on a Run that did not end objective_met), 1 carry internal names (1 on such a Run)
//   fix-291: 1 of 17 Answer(s) name the stop (1 of 3 on a Run that did not end objective_met), 1 carry internal names (0 on such a Run)
//   fix-311-312: 0 of 17 Answer(s) name the stop (0 of 1 on a Run that did not end objective_met), 1 carry internal names (0 on such a Run)
//   flash-orch: 0 of 16 Answer(s) name the stop (0 of 12 on a Run that did not end objective_met), 1 carry internal names (1 on such a Run)
//   jev-off: 1 of 17 Answer(s) name the stop (1 of 5 on a Run that did not end objective_met), 0 carry internal names (0 on such a Run)
//   jev-on: 0 of 17 Answer(s) name the stop (0 of 2 on a Run that did not end objective_met), 1 carry internal names (0 on such a Run)
//   main-4dc72e9: 1 of 18 Answer(s) name the stop (1 of 4 on a Run that did not end objective_met), 1 carry internal names (1 on such a Run)

import type { RecountedNamings } from './answerNamingRecount.ts'

/**
 * The capture sets whose traces were read: an attempt of one with no entry
 * below was answered by a model and its Answer carried no phrase. A set that
 * is not listed had no trace on disk.
 */
export const ANSWER_NAMING_SETS_RECOUNTED: readonly string[] = ["baseline-1","baseline-2","baseline-3","baseline2-1","baseline2-2","baseline2-3","baseline3-1","baseline3-2","baseline3-3","fix-250-1","fix-250-2","fix-250-3","fix-252-1","fix-252-2","fix-252-3","fix-253-256-1","fix-253-256-2","fix-253-256-3","fix-256r-1","fix-256r-2","fix-256r-3","fix-257-1","fix-257-2","fix-257-3","fix-258-259-1","fix-258-259-2","fix-258-259-3","fix-260-262-1","fix-260-262-2","fix-260-262-3","fix-263-264-1","fix-263-264-2","fix-263-264-3","fix-265-267-1","fix-265-267-2","fix-265-267-3","fix-265-267-4","fix-265-267-5","fix-270-1","fix-270-2","fix-270-3","fix-281-1","fix-281-2","fix-281-3","fix-283-1","fix-283-2","fix-283-3","fix-284-1","fix-284-2","fix-284-3","fix-288-290-1","fix-288-290-2","fix-288-290-3","fix-291-1","fix-291-2","fix-291-4","fix-311-312-1","fix-311-312-2","fix-311-312-3","flash-orch-1","flash-orch-2","flash-orch-3","jev-off-1","jev-off-2","jev-off-3","jev-on-1","jev-on-2","jev-on-3","main-4dc72e9-1","main-4dc72e9-2","main-4dc72e9-3"]

/** The attempts in which the user met no model-written Answer: none at all, or the Deterministic Answer. */
export const ANSWER_NAMING_UNANSWERED: readonly { readonly captureId: string; readonly attemptId: string }[] = [
  {"captureId":"baseline3-2--historical-longitude-watch","attemptId":"historical-longitude-watch--initial"},
  {"captureId":"baseline3-3--superseded-voyager-interstellar","attemptId":"superseded-voyager-interstellar--initial"},
  {"captureId":"fix-250-2--superseded-voyager-interstellar","attemptId":"superseded-voyager-interstellar--initial"},
  {"captureId":"fix-252-2--compatibility-pi-camera","attemptId":"compatibility-pi-camera--initial"},
  {"captureId":"fix-256r-2--historical-longitude-watch","attemptId":"historical-longitude-watch--initial"},
  {"captureId":"fix-258-259-2--superseded-voyager-interstellar","attemptId":"superseded-voyager-interstellar--initial"},
  {"captureId":"fix-258-259-3--historical-longitude-watch","attemptId":"historical-longitude-watch--initial"},
  {"captureId":"fix-260-262-1--historical-longitude-watch","attemptId":"historical-longitude-watch--initial"},
  {"captureId":"fix-263-264-2--historical-longitude-watch","attemptId":"historical-longitude-watch--initial"},
  {"captureId":"fix-265-267-5--compatibility-pi-camera","attemptId":"compatibility-pi-camera--initial"},
  {"captureId":"fix-265-267-5--superseded-voyager-interstellar","attemptId":"superseded-voyager-interstellar--initial"},
  {"captureId":"fix-281-1--superseded-voyager-interstellar","attemptId":"superseded-voyager-interstellar--initial"},
  {"captureId":"fix-281-2--compatibility-pi-camera","attemptId":"compatibility-pi-camera--follow_up"},
  {"captureId":"fix-288-290-1--compatibility-pi-camera","attemptId":"compatibility-pi-camera--initial"},
  {"captureId":"fix-291-1--superseded-voyager-interstellar","attemptId":"superseded-voyager-interstellar--initial"},
  {"captureId":"fix-311-312-1--compatibility-pi-camera","attemptId":"compatibility-pi-camera--follow_up"},
  {"captureId":"flash-orch-1--superseded-voyager-interstellar","attemptId":"superseded-voyager-interstellar--initial"},
  {"captureId":"flash-orch-3--compatibility-pi-camera","attemptId":"compatibility-pi-camera--initial"},
  {"captureId":"jev-off-1--superseded-voyager-interstellar","attemptId":"superseded-voyager-interstellar--initial"},
  {"captureId":"jev-on-2--compatibility-pi-camera","attemptId":"compatibility-pi-camera--initial"},
]

/** Every attempt whose Answer names the stop or carries an internal name, with where each phrase was read. */
export const ANSWER_NAMING_MARKS: readonly RecountedNamings[] = [
  {"captureId":"baseline-1--compatibility-pi-camera","attemptId":"compatibility-pi-camera--initial","stop":[{"where":"display","phrase":"before the run ended"}],"internal":[{"where":"display","phrase":"this session"}]},
  {"captureId":"baseline-1--historical-longitude-watch","attemptId":"historical-longitude-watch--initial","stop":[{"where":"speak","phrase":"ran out of browsing budget"},{"where":"display","phrase":"budget ran out"}],"internal":[]},
  {"captureId":"baseline-1--rule-eurostar-luggage","attemptId":"rule-eurostar-luggage--initial","stop":[],"internal":[{"where":"display","phrase":"run_note"},{"where":"display","phrase":"memory_patch"},{"where":"display","phrase":"mishear_proposals"},{"where":"display","phrase":"finalization_cause"},{"where":"display","phrase":"evidence_ids"}]},
  {"captureId":"baseline-1--rule-eurostar-luggage","attemptId":"rule-eurostar-luggage--follow_up","stop":[],"internal":[{"where":"display","phrase":"this run"}]},
  {"captureId":"baseline-2--compatibility-pi-camera","attemptId":"compatibility-pi-camera--initial","stop":[],"internal":[{"where":"display","phrase":"this run"}]},
  {"captureId":"baseline-2--rule-eurostar-luggage","attemptId":"rule-eurostar-luggage--follow_up","stop":[],"internal":[{"where":"display","phrase":"this session"}]},
  {"captureId":"baseline-3--superseded-voyager-interstellar","attemptId":"superseded-voyager-interstellar--initial","stop":[{"where":"speak","phrase":"time ran out"},{"where":"display","phrase":"browsing window"}],"internal":[{"where":"display","phrase":"this run"},{"where":"display","phrase":"this run"}]},
  {"captureId":"baseline2-1--historical-longitude-watch","attemptId":"historical-longitude-watch--initial","stop":[{"where":"speak","phrase":"ran out of time"}],"internal":[{"where":"display","phrase":"this run"}]},
  {"captureId":"baseline2-1--superseded-voyager-interstellar","attemptId":"superseded-voyager-interstellar--initial","stop":[],"internal":[{"where":"display","phrase":"this run"}]},
  {"captureId":"baseline2-2--compatibility-pi-camera","attemptId":"compatibility-pi-camera--initial","stop":[],"internal":[{"where":"display","phrase":"subagent"}]},
  {"captureId":"baseline2-2--superseded-voyager-interstellar","attemptId":"superseded-voyager-interstellar--initial","stop":[],"internal":[{"where":"display","phrase":"this run"}]},
  {"captureId":"baseline3-2--superseded-voyager-interstellar","attemptId":"superseded-voyager-interstellar--initial","stop":[{"where":"speak","phrase":"time ran out"},{"where":"display","phrase":"working time"},{"where":"asked_item","phrase":"working time"}],"internal":[{"where":"display","phrase":"this run"},{"where":"asked_item","phrase":"this run"}]},
  {"captureId":"fix-250-1--historical-longitude-watch","attemptId":"historical-longitude-watch--initial","stop":[{"where":"speak","phrase":"ran out of time"},{"where":"asked_item","phrase":"work budget"}],"internal":[{"where":"display","phrase":"this run"}]},
  {"captureId":"fix-250-1--rule-eurostar-luggage","attemptId":"rule-eurostar-luggage--initial","stop":[],"internal":[{"where":"display","phrase":"this run"}]},
  {"captureId":"fix-252-1--compatibility-pi-camera","attemptId":"compatibility-pi-camera--initial","stop":[],"internal":[{"where":"display","phrase":"this run"}]},
  {"captureId":"fix-252-1--historical-longitude-watch","attemptId":"historical-longitude-watch--initial","stop":[{"where":"speak","phrase":"budget ended"},{"where":"display","phrase":"before the run ended"},{"where":"asked_item","phrase":"before the run ended"}],"internal":[]},
  {"captureId":"fix-252-2--historical-longitude-watch","attemptId":"historical-longitude-watch--initial","stop":[{"where":"speak","phrase":"ran out of time"},{"where":"display","phrase":"before the run ended"}],"internal":[]},
  {"captureId":"fix-252-2--superseded-voyager-interstellar","attemptId":"superseded-voyager-interstellar--initial","stop":[{"where":"display","phrase":"within this run"}],"internal":[{"where":"display","phrase":"this run"}]},
  {"captureId":"fix-252-3--historical-longitude-watch","attemptId":"historical-longitude-watch--initial","stop":[{"where":"speak","phrase":"ran out of time"},{"where":"display","phrase":"budget ran out"},{"where":"asked_item","phrase":"budget exhaustion"}],"internal":[]},
  {"captureId":"fix-253-256-1--compatibility-pi-camera","attemptId":"compatibility-pi-camera--follow_up","stop":[],"internal":[{"where":"asked_item","phrase":"memory-7"},{"where":"asked_item","phrase":"memory-9"},{"where":"asked_item","phrase":"memory-8"},{"where":"asked_item","phrase":"memory-11"},{"where":"asked_item","phrase":"memory-4"},{"where":"asked_item","phrase":"memory-2"},{"where":"asked_item","phrase":"memory-5"}]},
  {"captureId":"fix-253-256-2--compatibility-pi-camera","attemptId":"compatibility-pi-camera--follow_up","stop":[],"internal":[{"where":"asked_item","phrase":"memory-6"},{"where":"asked_item","phrase":"memory-2"},{"where":"asked_item","phrase":"memory-4"}]},
  {"captureId":"fix-253-256-2--historical-longitude-watch","attemptId":"historical-longitude-watch--initial","stop":[{"where":"display","phrase":"before the run ended"},{"where":"asked_item","phrase":"work budget"}],"internal":[]},
  {"captureId":"fix-253-256-3--historical-longitude-watch","attemptId":"historical-longitude-watch--initial","stop":[{"where":"display","phrase":"before the run ended"},{"where":"asked_item","phrase":"before the run ended"}],"internal":[]},
  {"captureId":"fix-253-256-3--rule-eurostar-luggage","attemptId":"rule-eurostar-luggage--follow_up","stop":[],"internal":[{"where":"display","phrase":"Asked items"}]},
  {"captureId":"fix-253-256-3--superseded-voyager-interstellar","attemptId":"superseded-voyager-interstellar--initial","stop":[],"internal":[{"where":"display","phrase":"this run"},{"where":"asked_item","phrase":"this run"}]},
  {"captureId":"fix-256r-1--superseded-voyager-interstellar","attemptId":"superseded-voyager-interstellar--initial","stop":[{"where":"speak","phrase":"ran out of working time"},{"where":"display","phrase":"deadline"},{"where":"asked_item","phrase":"deadline"}],"internal":[{"where":"display","phrase":"this run"},{"where":"asked_item","phrase":"this run"},{"where":"asked_item","phrase":"this run"},{"where":"asked_item","phrase":"this run"},{"where":"asked_item","phrase":"this run"},{"where":"asked_item","phrase":"this run"}]},
  {"captureId":"fix-256r-3--compatibility-pi-camera","attemptId":"compatibility-pi-camera--initial","stop":[{"where":"display","phrase":"before the run ended"}],"internal":[]},
  {"captureId":"fix-256r-3--historical-longitude-watch","attemptId":"historical-longitude-watch--initial","stop":[],"internal":[{"where":"asked_item","phrase":"this run"}]},
  {"captureId":"fix-257-1--compatibility-pi-camera","attemptId":"compatibility-pi-camera--initial","stop":[],"internal":[{"where":"display","phrase":"asked items"}]},
  {"captureId":"fix-257-1--historical-longitude-watch","attemptId":"historical-longitude-watch--initial","stop":[{"where":"display","phrase":"work stopped before"},{"where":"asked_item","phrase":"before work stopped"}],"internal":[]},
  {"captureId":"fix-257-3--superseded-voyager-interstellar","attemptId":"superseded-voyager-interstellar--initial","stop":[{"where":"asked_item","phrase":"budget closed"}],"internal":[]},
  {"captureId":"fix-258-259-1--historical-longitude-watch","attemptId":"historical-longitude-watch--initial","stop":[{"where":"speak","phrase":"ran out of time"},{"where":"display","phrase":"work ran out"},{"where":"asked_item","phrase":"before work ended"}],"internal":[{"where":"asked_item","phrase":"this run"}]},
  {"captureId":"fix-258-259-2--historical-longitude-watch","attemptId":"historical-longitude-watch--initial","stop":[],"internal":[{"where":"display","phrase":"this run"},{"where":"asked_item","phrase":"this run"},{"where":"asked_item","phrase":"this run"}]},
  {"captureId":"fix-260-262-1--compatibility-pi-camera","attemptId":"compatibility-pi-camera--follow_up","stop":[],"internal":[{"where":"asked_item","phrase":"memory-5"}]},
  {"captureId":"fix-260-262-2--superseded-voyager-interstellar","attemptId":"superseded-voyager-interstellar--initial","stop":[],"internal":[{"where":"asked_item","phrase":"memory-2"},{"where":"asked_item","phrase":"memory-3"},{"where":"asked_item","phrase":"memory-1"},{"where":"asked_item","phrase":"memory-3"},{"where":"asked_item","phrase":"memory-2"},{"where":"asked_item","phrase":"memory-2"},{"where":"asked_item","phrase":"memory-3"}]},
  {"captureId":"fix-260-262-3--compatibility-pi-camera","attemptId":"compatibility-pi-camera--initial","stop":[],"internal":[{"where":"display","phrase":"Asked items"}]},
  {"captureId":"fix-260-262-3--compatibility-pi-camera","attemptId":"compatibility-pi-camera--follow_up","stop":[],"internal":[{"where":"display","phrase":"this session"}]},
  {"captureId":"fix-260-262-3--historical-longitude-watch","attemptId":"historical-longitude-watch--initial","stop":[],"internal":[{"where":"display","phrase":"vision timed out"},{"where":"display","phrase":"reader proxy"}]},
  {"captureId":"fix-263-264-1--rule-eurostar-luggage","attemptId":"rule-eurostar-luggage--follow_up","stop":[],"internal":[{"where":"display","phrase":"Session Evidence"}]},
  {"captureId":"fix-263-264-1--superseded-voyager-interstellar","attemptId":"superseded-voyager-interstellar--initial","stop":[],"internal":[{"where":"display","phrase":"this run"},{"where":"asked_item","phrase":"this session"}]},
  {"captureId":"fix-263-264-2--compatibility-pi-camera","attemptId":"compatibility-pi-camera--follow_up","stop":[],"internal":[{"where":"display","phrase":"this run"},{"where":"asked_item","phrase":"memory-1"}]},
  {"captureId":"fix-263-264-2--superseded-voyager-interstellar","attemptId":"superseded-voyager-interstellar--initial","stop":[],"internal":[{"where":"asked_item","phrase":"memory-5"},{"where":"asked_item","phrase":"memory-4"},{"where":"asked_item","phrase":"memory-3"},{"where":"asked_item","phrase":"memory-1"},{"where":"asked_item","phrase":"memory-3"},{"where":"asked_item","phrase":"memory-3"},{"where":"asked_item","phrase":"memory-2"},{"where":"asked_item","phrase":"memory-3"},{"where":"asked_item","phrase":"memory-1"},{"where":"asked_item","phrase":"memory-3"}]},
  {"captureId":"fix-263-264-3--historical-longitude-watch","attemptId":"historical-longitude-watch--initial","stop":[{"where":"asked_item","phrase":"budget closed"}],"internal":[]},
  {"captureId":"fix-265-267-3--compatibility-pi-camera","attemptId":"compatibility-pi-camera--initial","stop":[],"internal":[{"where":"display","phrase":"Asked item"}]},
  {"captureId":"fix-265-267-3--compatibility-pi-camera","attemptId":"compatibility-pi-camera--follow_up","stop":[],"internal":[{"where":"display","phrase":"asked item"},{"where":"display","phrase":"asked item"},{"where":"display","phrase":"asked item"}]},
  {"captureId":"fix-265-267-4--superseded-voyager-interstellar","attemptId":"superseded-voyager-interstellar--initial","stop":[],"internal":[{"where":"asked_item","phrase":"this run"}]},
  {"captureId":"fix-270-2--historical-longitude-watch","attemptId":"historical-longitude-watch--initial","stop":[],"internal":[{"where":"display","phrase":"this run"},{"where":"display","phrase":"asked items"},{"where":"display","phrase":"this run"},{"where":"asked_item","phrase":"this run"},{"where":"asked_item","phrase":"this run"}]},
  {"captureId":"fix-281-1--rule-eurostar-luggage","attemptId":"rule-eurostar-luggage--initial","stop":[],"internal":[{"where":"display","phrase":"run_note"},{"where":"display","phrase":"memory_patch"},{"where":"display","phrase":"mishear_proposals"},{"where":"display","phrase":"finalization_cause"},{"where":"display","phrase":"evidence_ids"}]},
  {"captureId":"fix-283-2--rule-eurostar-luggage","attemptId":"rule-eurostar-luggage--follow_up","stop":[],"internal":[{"where":"asked_item","phrase":"memory-5"},{"where":"asked_item","phrase":"memory-1"}]},
  {"captureId":"fix-283-3--rule-eurostar-luggage","attemptId":"rule-eurostar-luggage--initial","stop":[],"internal":[{"where":"display","phrase":"Asked items"}]},
  {"captureId":"fix-288-290-2--superseded-voyager-interstellar","attemptId":"superseded-voyager-interstellar--initial","stop":[{"where":"display","phrase":"ran out of run budget"}],"internal":[]},
  {"captureId":"fix-288-290-3--historical-longitude-watch","attemptId":"historical-longitude-watch--initial","stop":[],"internal":[{"where":"display","phrase":"this session"}]},
  {"captureId":"fix-291-1--compatibility-pi-camera","attemptId":"compatibility-pi-camera--follow_up","stop":[],"internal":[{"where":"display","phrase":"this run"},{"where":"asked_item","phrase":"this run"}]},
  {"captureId":"fix-291-4--historical-longitude-watch","attemptId":"historical-longitude-watch--initial","stop":[{"where":"speak","phrase":"budget closed"}],"internal":[]},
  {"captureId":"fix-311-312-2--compatibility-pi-camera","attemptId":"compatibility-pi-camera--initial","stop":[],"internal":[{"where":"display","phrase":"this session"}]},
  {"captureId":"flash-orch-2--compatibility-pi-camera","attemptId":"compatibility-pi-camera--follow_up","stop":[],"internal":[{"where":"display","phrase":"this session"}]},
  {"captureId":"jev-off-2--superseded-voyager-interstellar","attemptId":"superseded-voyager-interstellar--initial","stop":[{"where":"display","phrase":"before the run closed"}],"internal":[]},
  {"captureId":"jev-on-2--compatibility-pi-camera","attemptId":"compatibility-pi-camera--follow_up","stop":[],"internal":[{"where":"display","phrase":"asked item"}]},
  {"captureId":"main-4dc72e9-1--compatibility-pi-camera","attemptId":"compatibility-pi-camera--initial","stop":[{"where":"display","phrase":"run's budget"}],"internal":[{"where":"display","phrase":"this run"}]},
]
