// GENERATED by `pnpm live:empty-landings` (#304) from the Run Traces of the
// captures on disk. Do not edit by hand: run the sweep where the captures are.
//
// 62 capture sets read, 372 attempts, 38 Empty Landings, 0 Page Reads that returned text from one.

import type { RecountedAttempt } from './emptyLandingRecount.ts'

/**
 * The capture sets whose traces were read: an attempt of one with no entry
 * below met no Empty Landing. A set that is not listed had no trace on disk,
 * and keeps the counts its audit wrote.
 */
export const EMPTY_LANDING_SETS_RECOUNTED: readonly string[] = ["baseline-1","baseline-2","baseline-3","baseline2-1","baseline2-2","baseline2-3","baseline3-1","baseline3-2","baseline3-3","fix-250-1","fix-250-2","fix-250-3","fix-252-1","fix-252-2","fix-252-3","fix-253-256-1","fix-253-256-2","fix-253-256-3","fix-256r-1","fix-256r-2","fix-256r-3","fix-257-1","fix-257-2","fix-257-3","fix-258-259-1","fix-258-259-2","fix-258-259-3","fix-260-262-1","fix-260-262-2","fix-260-262-3","fix-263-264-1","fix-263-264-2","fix-263-264-3","fix-265-267-1","fix-265-267-2","fix-265-267-3","fix-265-267-4","fix-265-267-5","fix-270-1","fix-270-2","fix-270-3","fix-281-1","fix-281-2","fix-281-3","fix-283-1","fix-283-2","fix-283-3","fix-284-1","fix-284-2","fix-284-3","fix-288-290-1","fix-288-290-2","fix-288-290-3","fix-291-1","fix-291-2","fix-291-4","jev-off-1","jev-off-2","jev-off-3","jev-on-1","jev-on-2","jev-on-3"]

/** Every attempt that met an Empty Landing, with where its rounds hold each and the Page Reads that returned text from one. */
export const EMPTY_LANDING_MARKS: readonly RecountedAttempt[] = [
  {"captureId":"baseline-1--compatibility-pi-camera","attemptId":"compatibility-pi-camera--initial","marks":[{"round":15,"call":0,"name":"navigate","host":"raw.githubusercontent.com"},{"round":18,"call":0,"name":"navigate","host":"raw.githubusercontent.com"},{"round":20,"call":0,"name":"navigate","host":"raw.githubusercontent.com"}]},
  {"captureId":"baseline-1--superseded-voyager-interstellar","attemptId":"superseded-voyager-interstellar--initial","marks":[{"round":11,"call":0,"name":"navigate","host":"web.archive.org"}]},
  {"captureId":"baseline-2--compatibility-pi-camera","attemptId":"compatibility-pi-camera--initial","marks":[{"round":10,"call":0,"name":"navigate","host":"raw.githubusercontent.com"},{"round":15,"call":0,"name":"navigate","host":"raw.githubusercontent.com"}]},
  {"captureId":"baseline3-1--compatibility-pi-camera","attemptId":"compatibility-pi-camera--initial","marks":[{"round":22,"call":0,"name":"navigate","host":"pip-assets.raspberrypi.com"}]},
  {"captureId":"baseline3-1--historical-longitude-watch","attemptId":"historical-longitude-watch--initial","marks":[{"round":1,"call":1,"name":"navigate","host":"www.rmg.co.uk"},{"round":11,"call":0,"name":"navigate","host":"www.rmg.co.uk"}]},
  {"captureId":"fix-250-3--historical-longitude-watch","attemptId":"historical-longitude-watch--initial","marks":[{"round":20,"call":0,"name":"navigate","host":"www.rmg.co.uk"},{"round":21,"call":0,"name":"navigate","host":"www.rmg.co.uk"}]},
  {"captureId":"fix-252-2--compatibility-pi-camera","attemptId":"compatibility-pi-camera--follow_up","marks":[{"round":14,"call":0,"name":"navigate","host":"www.bing.com"}]},
  {"captureId":"fix-253-256-2--compatibility-pi-camera","attemptId":"compatibility-pi-camera--follow_up","marks":[{"round":13,"call":0,"name":"navigate","host":"pip-assets.raspberrypi.com"}]},
  {"captureId":"fix-257-1--superseded-voyager-interstellar","attemptId":"superseded-voyager-interstellar--initial","marks":[{"round":16,"call":1,"name":"navigate","host":"web.archive.org"}]},
  {"captureId":"fix-257-2--compatibility-pi-camera","attemptId":"compatibility-pi-camera--follow_up","marks":[{"round":7,"call":0,"name":"navigate","host":"pip-assets.raspberrypi.com"}]},
  {"captureId":"fix-257-2--historical-longitude-watch","attemptId":"historical-longitude-watch--initial","marks":[{"round":7,"call":0,"name":"navigate","host":"www.rmg.co.uk"}]},
  {"captureId":"fix-260-262-2--superseded-voyager-interstellar","attemptId":"superseded-voyager-interstellar--initial","marks":[{"round":9,"call":0,"name":"navigate","host":"web.archive.org"}]},
  {"captureId":"fix-260-262-3--historical-longitude-watch","attemptId":"historical-longitude-watch--initial","marks":[{"round":1,"call":1,"name":"navigate","host":"www.rmg.co.uk"},{"round":8,"call":0,"name":"navigate","host":"www.rmg.co.uk"},{"round":18,"call":0,"name":"navigate","host":"www.rmg.co.uk"}]},
  {"captureId":"fix-265-267-1--compatibility-pi-camera","attemptId":"compatibility-pi-camera--initial","marks":[{"round":13,"call":2,"name":"navigate","host":"pip-assets.raspberrypi.com"}]},
  {"captureId":"fix-265-267-4--historical-longitude-watch","attemptId":"historical-longitude-watch--initial","marks":[{"round":9,"call":0,"name":"navigate","host":"www.rmg.co.uk"}]},
  {"captureId":"fix-270-2--compatibility-pi-camera","attemptId":"compatibility-pi-camera--follow_up","marks":[{"round":13,"call":0,"name":"navigate","host":"pip-assets.raspberrypi.com"}]},
  {"captureId":"fix-270-2--historical-longitude-watch","attemptId":"historical-longitude-watch--initial","marks":[{"round":11,"call":0,"name":"navigate","host":"www.rmg.co.uk"}]},
  {"captureId":"fix-270-3--superseded-voyager-interstellar","attemptId":"superseded-voyager-interstellar--initial","marks":[{"round":2,"call":0,"name":"navigate","host":"www.jpl.nasa.gov"}]},
  {"captureId":"fix-281-1--historical-longitude-watch","attemptId":"historical-longitude-watch--initial","marks":[{"round":5,"call":1,"name":"navigate","host":"www.rmg.co.uk"}]},
  {"captureId":"fix-284-2--historical-longitude-watch","attemptId":"historical-longitude-watch--initial","marks":[{"round":4,"call":0,"name":"navigate","host":"www.rmg.co.uk"}]},
  {"captureId":"fix-288-290-1--historical-longitude-watch","attemptId":"historical-longitude-watch--initial","marks":[{"round":1,"call":1,"name":"navigate","host":"www.rmg.co.uk"},{"round":2,"call":0,"name":"navigate","host":"www.rmg.co.uk"},{"round":7,"call":0,"name":"navigate","host":"www.rmg.co.uk"},{"round":13,"call":0,"name":"navigate","host":"www.rmg.co.uk"}]},
  {"captureId":"fix-288-290-3--historical-longitude-watch","attemptId":"historical-longitude-watch--initial","marks":[{"round":2,"call":0,"name":"navigate","host":"www.rmg.co.uk"},{"round":5,"call":0,"name":"navigate","host":"www.rmg.co.uk"},{"round":6,"call":0,"name":"navigate","host":"www.rmg.co.uk"},{"round":8,"call":0,"name":"navigate","host":"www.rmg.co.uk"}]},
  {"captureId":"jev-on-1--historical-longitude-watch","attemptId":"historical-longitude-watch--initial","marks":[{"round":1,"call":1,"name":"navigate","host":"www.rmg.co.uk"},{"round":3,"call":0,"name":"navigate","host":"www.rmg.co.uk"}]},
  {"captureId":"jev-on-2--historical-longitude-watch","attemptId":"historical-longitude-watch--initial","marks":[{"round":22,"call":0,"name":"navigate","host":"www.rmg.co.uk"}]},
]
